/**
 * Error Codes
 */
module.exports = {
  STATUS_NO_ERROR: 0,
  FAILED_GET_SECRET_VALUE: 1000,
  HTTP_GET_REQ_TO_CX_FAILED: 1001,
  HTTP_POST_REQ_TO_CX_FAILED: 1002,
  HTTP_REQ_TO_SF_FAILED: 1003,
  FAILED_GET_PSR: 1004,
  EUREKA_CLIENT_FAILURE: 1005,
  FAILED_SEND_REQUEST_TO_XMS: 1006,
};
